### ISSUE TITLE
Multiple printer support

### ISSUE THREAD

**Issue by jacobnilsson89** [Aetrius/Bambulabs-Exporter#21]
Hello

I'm struggling to add more printers to collect data from. I want to use one "collect-host" (ubuntu). One printer is working fine but I'm not sure how best to add more printers to the collector. Please advice.

**Comment by Aetrius** [comment]
Good point. Ill look into it, normally you'd make scrape targets and pass data via http/https to the endpoints. 

For now you can run additional copies of the exporter on different configs/ports if necessary. Running this in kubernetes simplifies this a bit 

global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "BambuLabs"
    scrape_interval: 15s
    static_configs:
    - targets: ["bambulabs-aetrius-exporter:9101"]

**Comment by jacobnilsson89** [comment]
Thank you for your reply. I tried copying my working exporter folder and edited the docker-compose file to use a different port and another name for the container. The container starts up but I'm not able to browse to the new container.
Maybe I missunderstod how to set up the file? This is my cloned config that is not working.
```
    container_name: bambulabs-aetrius-exporterNV
    ports:
      - "9102:9102"
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge
```
The container runs fine and this is what I see in the running log:
Starting Exporter: %!(EXTRA string=2024-10-17 06:48:29.387027411 +0000 UTC m=+0.003189480)
Env Vars Loaded

Again, thanks for your reply and thank you for this awesome exporter tool :)

**Comment by mrjones-plip** [comment]
@jacobnilsson89 - I'm not sure if you're still having an issue trying to monitor multiple printers, but I was able to get this working.  I don't have my printers handy to test end to end, but I was able to do a mock deployment with this compose file. It assume your printers are named `bobby` and `lisa` (salt to taste!):

`compose.yml`:

```yaml
services:
  bobby:
    image: aetrius/bambulabs-exporter
    env_file: .env
    ports:
      - "9101:9101"
  lisa:
    image: aetrius/bambulabs-exporter
    env_file: .env2
    ports:
      - "9102:9101"
```

Then start them both up with this docker call:

```
$ docker compose up -d
```

Check they're running with `docker` and `curl`:

```
$ docker ps --format="{{.Names}}"
bambulabs-exporter-lisa-1
bambulabs-exporter-bobby-1

$ curl localhost:9102
<html><head><title>BambuLabs Exporter Metrics</title></head><body>
                        <h1>BambuLabs Exporter</h1><p><a href='/metrics'>Metrics</a></p></body>
                        </html>

$ curl localhost:9101
<html><head><title>BambuLabs Exporter Metrics</title></head><body>
                        <h1>BambuLabs Exporter</h1><p><a href='/metrics'>Metrics</a></p></body>
                        </html>
```

best of luck!
